---
title: Ilikelinux69.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: I Like Linux
description: Linux and FOSS enthusiast
avatar: https://avatars.githubusercontent.com/ilikelinux69
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: ilikelinux69
  instagram: 
  linkedin: 
  pinterest: 
  rss: RSS-Feed
  twitter: ilikelinux69
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: ilikelinux
google_analytics: 
url: ilikelinux69.github.io
baseurl: ''
markdown: kramdown
highlighter: rouge
permalink: "/:title/"
version: v1.1.0
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
